const data = [
  {
    day: 1,
    name: "Contains Duplicate",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/contains-duplicate",
  },
  {
    day: 2,
    name: "Valid Anagram",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/valid-anagram",
  },
  {
    day: 3,
    name: "Two Sum",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/two-sum",
  },
  {
    day: 4,
    name: "Group Anagrams",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/group-anagrams",
  },
  {
    day: 5,
    name: "Top K Frequent Elements",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/top-k-frequent-elements",
  },
  {
    day: 6,
    name: "Valid Sudoku",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/valid-sudoku",
  },
  {
    day: 7,
    name: "Product of Array Except Self",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/product-of-array-except-self",
  },
  {
    day: 8,
    name: "Longest Consecutive Sequence",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/longest-consecutive-sequence",
  },
  {
    day: 9,
    name: "Valid Palindrome",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/valid-palindrome",
  },
  {
    day: 10,
    name: "Two Sum II Input Array Is Sorted",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted",
  },
  {
    day: 11,
    name: "3Sum",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/3sum",
  },
  {
    day: 12,
    name: "Container With Most Water",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/container-with-most-water",
  },
  {
    day: 13,
    name: "Best Time to Buy And Sell Stock",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock",
  },
  {
    day: 14,
    name: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/longest-substring-without-repeating-characters",
  },
  {
    day: 15,
    name: "Longest Repeating Character Replacement",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/longest-repeating-character-replacement",
  },
  {
    day: 16,
    name: "Valid Parentheses",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/valid-parentheses",
  },
  {
    day: 17,
    name: "Min Stack",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/min-stack",
  },
  {
    day: 18,
    name: "Daily Temperatures",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/daily-temperatures",
  },
  {
    day: 19,
    name: "Binary Search",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/binary-search",
  },
  {
    day: 20,
    name: "Find Minimum In Rotated Sorted Array",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array",
  },
  {
    day: 21,
    name: "Search In Rotated Sorted Array",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/search-in-rotated-sorted-array",
  },
  {
    day: 22,
    name: "Reverse Linked List",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/reverse-linked-list",
  },
  {
    day: 23,
    name: "Merge Two Sorted Lists",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/merge-two-sorted-lists",
  },
  {
    day: 24,
    name: "Reorder List",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/reorder-list",
  },
  {
    day: 25,
    name: "Remove Nth Node From End of List",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list",
  },
  {
    day: 26,
    name: "Linked List Cycle",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/linked-list-cycle",
  },
  {
    day: 27,
    name: "LRU Cache",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/lru-cache",
  },
  {
    day: 28,
    name: "Invert Binary Tree",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/invert-binary-tree",
  },
  {
    day: 29,
    name: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/maximum-depth-of-binary-tree",
  },
  {
    day: 30,
    name: "Diameter of Binary Tree",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/diameter-of-binary-tree",
  },
  {
    day: 31,
    name: "Balanced Binary Tree",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/balanced-binary-tree",
  },
  {
    day: 32,
    name: "Same Tree",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/same-tree",
  },
  {
    day: 33,
    name: "Subtree of Another Tree",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/subtree-of-another-tree",
  },
  {
    day: 34,
    name: "Lowest Common Ancestor of a Binary Search Tree",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree",
  },
  {
    day: 35,
    name: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/binary-tree-level-order-traversal",
  },
  {
    day: 36,
    name: "Binary Tree Right Side View",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/binary-tree-right-side-view",
  },
  {
    day: 37,
    name: "Count Good Nodes In Binary Tree",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/count-good-nodes-in-binary-tree",
  },
  {
    day: 38,
    name: "Validate Binary Search Tree",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/validate-binary-search-tree",
  },
  {
    day: 39,
    name: "Kth Smallest Element In a Bst",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/kth-smallest-element-in-a-bst",
  },
  {
    day: 40,
    name: "Kth Largest Element In a Stream",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/kth-largest-element-in-a-stream",
  },
  {
    day: 41,
    name: "Last Stone Weight",
    difficulty: "Easy",
    link: "https://leetcode.com/problems/last-stone-weight",
  },
  {
    day: 42,
    name: "Kth Largest Element In An Array",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/kth-largest-element-in-an-array",
  },
  {
    day: 43,
    name: "Number of Islands",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/number-of-islands",
  },
  {
    day: 44,
    name: "Max Area of Island",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/max-area-of-island",
  },
  {
    day: 45,
    name: "Clone Graph",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/clone-graph",
  },
  {
    day: 46,
    name: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/pacific-atlantic-water-flow",
  },
  {
    day: 47,
    name: "Surrounded Regions",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/surrounded-regions",
  },
  {
    day: 48,
    name: "Course Schedule",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/course-schedule",
  },
  {
    day: 49,
    name: "Course Schedule II",
    difficulty: "Medium",
    link: "https://leetcode.com/problems/course-schedule-ii",
  },
];

export default data;
